### ISSUE TITLE
Add steps with focus

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#130]
What do you think about adding a focus step?

```
And the "..." field should be focused
And the focused field should contain "..." 
```

**Comment by judithroth** [comment]
I can't remember that I needed to use this step in any application. In my opinion this is too specific for spreewald.

**Comment by codener** [comment]
I think this step (set) is generic enough to be in Spreewald. However, even in large projects I have only seen them rarely used, and mostly in a customized way: "When I press enter in the focused field".

Since [testing focus in parallel has issues](https://github.com/makandra/geordi/blob/e9aba4901924c7fcdf8d69bbb6f8d8ba6496c11e/lib/geordi/commands/cucumber.rb#L9-L10) anyway, I suggest to not encourage users to test focus and let them define their own steps when needed.

**Comment by judithroth** [comment]
We clearly decided against this, so I'm closing this issue. Thank your for the suggestion and for voting :)
