### ISSUE TITLE
Rework email steps

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#132]
This is a partial extract of #52, which I closed in favor of this issue. What do you think about these changes in the email steps?

1. Improve all error messages for existing email steps:
   * Improve the error message if an email could not be found (see https://github.com/makandra/spreewald/issues/52#issue-78572534 and https://github.com/makandra/spreewald/issues/52#issuecomment-343445340 for more details)
   * Improve the error message if the content does not match. I always want to copy and paste directly from the error message.

   It would make the step `Then show me the e?mails` redundant, if the error messages are good enough. It might be useful to write the complete `.eml` file to `tmp/` and print the path to the user, as it is the best way to figure out more complex issues with attachments.

2. `Then an email should have been sent with:` and `And that mail should have the following lines in  the body` have an undocumented dependency. It only works in this order.

3. A fuzzy matching email step, more advanced than the current behavior:
   > You may skip lines in the header, of course. Note that the mail body is only checked for inclusion. That means you can only test a prefix of the body. The subject may also be a prefix.

   > You may skip lines, of course. Note that you may also omit text at the end of each line.

   I would be happy to write `.*`, which would be more explizit than the magic ignore lines and suffix feature. Maybe it allows to skip whole lines.

**Comment by triskweline** [comment]
As a Spreewald maintainer I hate that we have different e-mail steps that do the same thing. I wish we just had `An e-mail should have been sent with:` and a text body, which looks like e-mail source code.

In our table steps we already use `*` as a placeholder for an arbitrary number of characters, so we could use the same here. I like this better than supporting full Regexp syntax (I don't want code in my Cucumber scenario).

New lines in the body can be treated like `*`. I don't expect newline characters to be present verbatim in the e-mail body, since it might have been wrapped due to line length limits or HTML.

**Comment by codener** [comment]
Agreeing with @triskweline.

About suggested change 1: Note that Spreewald's e-mail steps currently log them to `log/test_mails.log`. That is the place where users already can check sent mail. However, it might be better to remove the logging altogether and print sent mail whenever an expected mail is not found, just like the "field should contain ..." step does.
In case we remove the mail logging, I would keep the "show me the emails" step just because it may be handy to see all sent mail (of a scenario) at a glance (like "show me the page").

Please do not forget all the details mentioned in #52.

The email steps refactoring is a big thing with many edge cases to consider. Please conduct thorough reviews and trials before releasing this.

**Comment by judithroth** [comment]
I totally agree on having `*` as a placeholder for text I don't care about. This is way better than beeing able to leave out lines (which nobody knows and nobody gets when reading the test).

I learned one thing from the multiple discussions around the email steps in the last months: Different people want to do different things.
In the discussions we had at least these wishes (which all seem valid to me):

- Match against the HTML mail with the HTML tags
- Match against the HTML mail with all tags stripped away
- Optional stripping of unnecessary whitespace (e.g. multiple spaces, newlines)

I can easily imagine that people also want to be able to test their plain text emails.
To cover these cases we would need something like this:
`Then an (html|plain text) email should have been sent with( [strip whitespace])?( [keep tags])?:`

**Comment by codener** [comment]
I think a literal testing of the mail body should be good enough, without stripping tags or white space. (The asterisk can be used for that.) For multipart emails, a special divider could be used. I'm not sure what divider to use, but my idea goes like this:

```
Then an e-mail should have been sent with:
"""
From: ...
To: ...
Subject: ...

Hello world!
=== or %%% or multipart/html: or whatever
<h1>Hello world!</h1>
"""
```

After all, Cucumber is only fit for testing simple mails with a few links, paragraphs and the like. As soon as complex HTML is involved, that mail should be specced IMHO.

**Comment by judithroth** [comment]
@codener you're right, additional whitespace or tags could be replaced by the asterisk. For me that would be good enough (and if people keep complaining about it we can still add the stripping later).

I don't like the idea of having a divider (because that's kind of secret knowledge and people have to read the documentation to find out what the separator looks like). So I would prefer to just write two steps or have an option. But if there is noone who wants to test plain text email I would say we leave that out as well until we actually have that usecase.

**Comment by foobear** [comment]
We have discussed this and worked through all the different requirements mentioned in this issue.

Here is what we will do.


1. Replace all different steps testing for e-mail headers/body/whatever and have a single remaining step that works like this:

       Then an e-mail should have been sent with:
       """
       From: ...
       To: ...
       Subject: ...
       
       Hello world!
       """

   If available, it prefers the HTML part and compares against its text content (as outlined in #111) or falls back to the plain-text part.
   
   You can say "an HTML e-mail" or "a plain-text email" to disable fallback behavior.
   
   Header fields and their values may be separated by multiple spaces to allow alignment of headers for those who fancy that. E.g.
   
       From:    ...
       To:      ...
       Subject: ...
   

2. Introduce `*` as a wildcard to omit the rest of a single line (like a randomized token in a URL) or entire lines, if the asterisk is the only character in a single line.

       Hello Alice!
       
       Click here to confirm your account:
       http://www.example.com/confirm?token=*
       
       *
       
       Bye!
       OmniCorp


3. Improve output of "email not found" error. Will be something like this:

       Could not find e-mail:
       From: ...
       To: ...
       Subject: ...
       
       Sent e-mails:
       ... (like "show me the emails" step, or similar)


4. Improve output when e-mail body does not match.
   - If a single e-mail could found for the given headers (e.g. recipient or subject), we might just do a "regular" text regexp match which results in a usable error message.
   - If there are multiple e-mails for the given headers, and no body matches, we show the "email not found" error which lists all e-mails.
