### ISSUE TITLE
3.0.3 comes with a regression for the e-mail step

### ISSUE THREAD

**Issue by makmic** [makandra/spreewald#161]
Before Spreewald 3.0.3, the general email step was able to assert mails without their text bodies. For example, this is no longer possible:
```
    Then an email should have been sent with:
      """
        Subject: My subject
      """
```

>       No matching mail was found. There were 1 mails in total.
>       1 of those had matching headers.

Removing [these recent changes](https://github.com/makandra/spreewald/pull/158/files#diff-5a4ab3a1a858411baea7d02b4ce18380da0163709097e4f79a2b75f66664aa07R18-R22) fixes it, please look at them again.

**Comment by FLeinzi** [comment]
Your example has revealed many more problems in the email steps:

When you indent a header line, it won't be recognized as part of the header. So in 3.0.2 your test was green, because the line was ignored. This was NOT introduced in 3.0.3 and seems to be a much older error. We have to investigate this further. 

Since 3.0.3 such a line will be mistakenly treated as part of the body. We should strip the lines before checking for a header line.

In 3.0.2 (and before) you can write almost everything in header-like style, e.g.:
```
Then an email should have been sent with:
  """
  FOOBAR: This line will be ignored
  """
```
and the step will succeed. Also for 3.0.3.

**Conclusion**: We have to rework the MailFinder and investigate how long this is an issue.

**Comment by judithroth** [comment]
> Before Spreewald 3.0.3, the general email step was able to assert mails without their text bodies.

I've taken a look at the mail steps today as well. Does the following work for you?

```
    Then an email should have been sent with:
      """
      Subject: My subject

      *
      """
```

I added a comment to the README of Spreewald a few minutes ago that the behavior of matching body lines has changed in recent versions. Before, lines that were not mentioned were omitted, now the asterisk is needed for that.

**Comment by judithroth** [comment]
I tested again and the asterisk is not necessary in case you only want to test the header. @FLeinzi had the correct suspicion :+1:
