### ISSUE TITLE
`rails_error?` method does not work for inputs nested deeper than one level

### ISSUE THREAD

**Issue by begerdom** [makandra/spreewald#205]
The rails error detection mechanism works only, if an input is placed as direct child under a container with the `field_with_errors` class, e.g. a `.form-group`. That is because it does only check for this class on the direct parent node. See https://github.com/makandra/spreewald/blob/master/lib/spreewald_support/field_errors.rb#L52

In my case the input is nested within an `.input-group` and the class cannot be found on this one, but is located a bit higher above.

The detection mechanism should rather search for the class on any parent and then check, if such a node can be found. Something like `@element.has_xpath?("ancestor-or-self::*[contains(@class, \"#field_with_errors\")]")` (compare to `custom_error?`.

For now, I can use the `custom_error?` by setting `Spreewald.field_error_class = 'field_with_errors'` to help because it does exactly that. However, I feel that this should also be the default behavior for the `rails_error?` method.

**Comment by kratob** [comment]
When we fix this: We also need to refactor this code for performance.

The `error_present?` method takes up to `4 * Capybara.default_max_wait_time` if there is  no error, since `has_xpath?` will wait if there is no match.

We have to use `has_no_xpath?` etc. according to whether we currently expect, or not expect there to  be an error.
