### ISSUE TITLE
Revert delegation of debugger step to console step

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#77]
I've noticed that I used quite often the step `Then debugger` to have a debugger in context of the cucumber world.

E.g. When I want to test why a radio button is not checked with the step 

```
And I choose "Ordered" within the order
```

then the original debugger step would be useful to paste into the console

```
with_scope('the order') { step('I choose "Ordered"') }
```

while watching the browser in VNC for changes.

The removal was introduced in https://github.com/makandra/spreewald/commit/aa7ae115261d6cf25fd495ad5e383d829da07e06. 

@codener Can we keep both debugger and console within spreewald?

**Comment by triskweline** [comment]
We removed the debugger since it often starved the thread running the Webrick for Selenium. So if the browser was making requests, it would never receive a server response while the debugger was on.

Maybe we could start the IRB with the `self` of the step. This way we could access `step`, `page`, `with_scope` etc. but without the debugger starving our test server.

It could work like this (kind of untested):

```
Then 'console' do
  irb_object = self
  IRB.setup(nil)
  workspace = IRB::WorkSpace.new(irb_object)
  irb = IRB::Irb.new(workspace)
  IRB.conf[:MAIN_CONTEXT] = irb.context
  irb.eval_input
end
```

**Comment by denzelem** [comment]
Done in c135b6d0ea1c8f7d5ffe4e13bd5a97a0bd8b0751.

**Comment by codener** [comment]
Awesome :tada:
